### ISSUE TITLE
setDestination([long, lat]) should preserve precision of coordinates

### ISSUE THREAD

**Issue by kbroderick** [mapbox/mapbox-gl-directions#156]
If I call setDestination([long, lat]) with four digits after the decimal, the values that end up in the destination field display usually many more decimal places (often 14) in an approximation of the original value.

For example, I call:
directionControl.setDestination([-105.963,35.6732]);
and then the display shows
-105.96299999999997,35.67319999999995
which is not only misrepresenting the precision of the original request, but not quite the same numbers, either.

**Comment by lbud** [comment]
This is some javascript floating point math funkiness; it's been partially fixed with https://github.com/mapbox/mapbox-gl-directions/blob/master/src/controls/geocoder.js#L181 (not yet in a release) but will preserve original mantissa length after https://github.com/mapbox/mapbox-gl-directions/pull/161.
