### ISSUE TITLE
Better request management on endpoint dragging

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-directions#36]
@tristen Currently the endpoint dragging is very laggy, because it sends too many requests. We can drastically improve the experience by doing two things:

1. Throttle or debounce the requests. They shouldn't fire more often than 200ms, maybe more.
2. Cancel outdated requests — when you move the mouse, only the latest position is relevant but requests for all previous points during the move still hang until completed. See GL JS for an example of request canceling (we do this for tiles).

![image](https://cloud.githubusercontent.com/assets/25395/11724258/d4f7281c-9f27-11e5-8e95-f9fcd8ffb20e.png)

**Comment by tristen** [comment]
>  See GL JS for an example of request canceling (we do this for tiles).

@mourner total #lazyweb but plz send link.

**Comment by mourner** [comment]
@tristen we [just call](https://github.com/mapbox/mapbox-gl-js/blob/ba9d1095ce5509595a0014a18037c4a3ba3b879d/js/source/worker.js#L66) `xhr.abort()` whenever we loose interest in a response of a request that hasn't completed yet.

**Comment by tristen** [comment]
Need to dig but _afaik_ this is currently block upstream in https://github.com/mapbox/mapbox-sdk-js.

**Comment by tristen** [comment]
Tying the pieces together here https://github.com/mapbox/mapbox-sdk-js/issues/89

**Comment by stevage** [comment]
This problem still seems to exist. When you drag an endpoint, dozens of requests are fired off really quickly. I don't know if the cancellation behaviour described above is happening, but it would still be better to debounce the requests, because:

1. That's a lot of network traffic
2. That's a lot of API requests
3. (Depending on whether the cancellation is happening) That's a lot of processing of the results
