### ISSUE TITLE
Don't reverse geocode coordinates before making a Directions request.

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox-gl-directions#43]
There's something janky going on when clicking to set origin / destination. I assume the code reverse geocodes a location and then updates the location returned? This leads to very weird behavior in areas where our geocoding locations are sparse:

![janky](https://cloud.githubusercontent.com/assets/98233/11831821/3d500c12-a3d8-11e5-8b0e-ab289fbc6b7c.gif)

**Comment by tristen** [comment]
I _think_ this is actually a data problem. cc @TheMarex

**Comment by tristen** [comment]
The UI error is being compounded with https://github.com/mapbox/mapbox-gl-directions/issues/36

**Comment by tristen** [comment]
This is a bit of a blunder on my end. The data that supports the geocoder doesn't have address data for South Korea. Because directions/geocoding data don't have parity (_i.e [this request](https://api.mapbox.com/geocoding/v5/mapbox.places/126.9634810471212%2C37.549620648822724.json?access_token=pk.eyJ1IjoidHJpc3RlbiIsImEiOiJiUzBYOEJzIn0.VyXs9qNWgTfABLzSI3YcrQ) always returns Seoul and not the address_) I shouldn't be piping coordinates to the geocoder first and making a Directions request from the reverse geocoded result of origin and destination. 

This is going to take some refactoring but its top priority for `v1.1.0`
