### ISSUE TITLE
Route does not appear

### ISSUE THREAD

**Issue by NathanVG** [mapbox/mapbox-gl-directions#92]
Route does not appear if both setDestination and setOrigin are set on initialisation, I have to hover above the directions for the route to appear.
![bug](https://cloud.githubusercontent.com/assets/3620183/18638405/4800224e-7e90-11e6-91ea-1417e7337f2b.gif)

**Comment by mapsam** [comment]
Hi @NathanVG - there have been a number of changes in gl-js and gl-directions since your ticket, apologies for the delay here! I'm testing out the following code with the upcoming `3.0.0` release and it seems to be working as expected:

```
map.on('load', () => {
  directions.setOrigin([-79.37960028993774,43.73794307719936]);
  directions.setDestination([-79.35868737779049,43.75471614887647]);
});
```

Note that in order to use these make sure they are wrapped in the `map.on('load', ...)`. If you update to 3.0.0, which will release shortly, you _must_ use mapbox-gl-js version `0.27.0` or greater.

**Comment by mapsam** [comment]
![mapbox-gl-directions-onload](https://cloud.githubusercontent.com/assets/1943001/20445298/5ca38cea-ad89-11e6-8921-652d0e7ad889.gif)

**Comment by mapsam** [comment]
This is resolved in [v3.x](https://github.com/mapbox/mapbox-gl-directions/releases)
